# Don't print a new line at the start of the prompt
add_newline = true

[git_status]
conflicted = "ğŸš¨ "
renamed = "ğŸ†• "
prefix = ""
suffix = " "
style = "bold magenta"

[git_branch]
symbol = "ğŸ™ "

[python]
symbol = "ğŸ "

[time]
disabled = false
format = "ğŸ•’ %T"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ’¨"
