# Don't print a new line at the start of the prompt
add_newline = true

[git_status]
conflicted = "ğŸš¨ "
renamed = "âš "
prefix = ""
suffix = " "
style = "bold magenta"

[git_branch]
symbol = "ğŸ™ "

[python]
symbol = "ğŸ "

[time]
disabled = false
format = "ğŸ•’ %T"
